apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automated-application
  namespace: argocd
spec:
  destination:
    namespace: automated-sync
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nginx
    repoURL: https://github.com/atharva-kulkarni123/argocd-projects.git
    targetRevision: main
  syncPolicy:
    automated: {}
